### ISSUE TITLE
Refactoring NewPostResponse

### ISSUE THREAD

**Issue by sOM2H** [nixsolutions/golang-echo-boilerplate#1]
I don't think we need to use [**append()**](https://github.com/nixsolutions/golang-echo-boilerplate/blob/064307679a9910be155f68b20ab81d501c273da6/responses/posts_response.go#L18) since we know the number of posts and [**append()**](https://github.com/nixsolutions/golang-echo-boilerplate/blob/064307679a9910be155f68b20ab81d501c273da6/responses/posts_response.go#L18) just slows down the function.

Better to do so:
```go
func NewPostResponse(posts []models.Post) *[]PostResponse {
	postResponse := make([]PostResponse, len(posts))

	for i, p := range posts {
		postResponse[i] = PostResponse{
			Title:    p.Title,
			Content:  p.Content,
			Username: p.User.Name,
			ID:       p.ID,
		}
	}

	return &postResponse
}
```

**Comment by pechenini** [comment]
Hello, it is a good idea. Please, create a PR to add this improvement.

**Comment by taras-seryogin** [comment]
not actual
